#!/bin/sh

config_dir="/etc/letsencrypt/renewal"
web_service="nginx"

le_path='/opt/letsencrypt'
exp_limit=30;

if [ ! -d $config_dir ]; then
        echo "[ERROR] config dir does not exist: $config_dir"
        exit 1;
fi
need_reload=0;
for config_file in `ls $config_dir/*.conf`; do
        echo Processing $config_file;
        domain=`grep "^\s*domains" $config_file | sed "s/^\s*domains\s*=\s*//" | sed 's/(\s*)\|,.*$//'`
        webroot_path=`grep "^\s*webroot_path" $config_file | sed "s/^\s*webroot_path\s*=\s*//" | sed 's/(\s*)\|,.*$//'`
        cert_file="/etc/letsencrypt/live/$domain/fullchain.pem"

        if [ ! -f $cert_file ]; then
                echo "[ERROR] certificate file not found for domain $domain."
        fi

        exp=$(date -d "`openssl x509 -in $cert_file -text -noout|grep "Not After"|cut -c 25-`" +%s)
        datenow=$(date -d "now" +%s)
        days_exp=$(echo \( $exp - $datenow \) / 86400 |bc)

        echo "Checking expiration date for $domain..."
        if [ "$days_exp" -gt "$exp_limit" ] ; then
                echo "The certificate is up to date, no need for renewal ($days_exp days left)."
        else
                echo "The certificate for $domain is about to expire soon. Starting webroot renewal script..."
                need_reload=1
                $le_path/letsencrypt-auto certonly --no-self-upgrade -a webroot --webroot-path=$webroot_path -d $domain --agree-tos --renew-by-default
        fi
        echo ""
done

if [ "$need_reload" -eq "1" ]; then
        echo "Reloading $web_service"
        service $web_service reload
fi